### ISSUE TITLE
Completely Broken

### ISSUE THREAD

**Issue by JWhitleyWork** [upowerrobotics/ros2_fabric#38]
While testing this repository in ROS Humble, I discovered the following:

1. With the default FastRTPS, you get an error when creating the publisher about an unknown QoS history policy.
2. With a recording of less than 60 seconds, `get_log.py` spits out a `numpy` error and produces an empty CSV.
3. With a recording of longer than 60 seconds, `get_log.py` *sometimes* spits out a `numpy` error and other times spits out a CSV with only a few lines in it.

**Comment by LawrenceXu13467** [comment]
Hi @JWhitleyWork. Good to see you again :)

Sorry to hear that it's broken. I guess it was just not completely done/tested for Humble. 

I am not too sure if Humble rmw time logging was previously implemented since I only see [closed PR ](https://github.com/upowerrobotics/rmw_fastrtps/pulls?q=is%3Apr+is%3Aclosed) based on Galactic. The current way get_log works would require all fields with values, and if rmw time missing then get_log wouldn't just give a partial output.   

However, I have just tested it under Galactic and it is still working correctly. I might need to install Humble and try that later.

**Comment by JWhitleyWork** [comment]
Hey, Lawrence! I actually discovered a ROS bug that plays into 1. See https://github.com/ros2/rclcpp/issues/2314. For the other two, I think the regexes are too broad and are catching lines in the log that they shouldn't be. I'm looking at solutions right now. 

So are you actually maintaining this? Because I have a handful of fixes but I don't want to overwhelm you if you're the only person still at U Power maintaining this project.

**Comment by JWhitleyWork** [comment]
Most of the issues are fixed with the PRs that I put in so I'm closing this.
